# Generated by Django 3.2.13 on 2023-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipsumuye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyeNo', models.IntegerField()),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('seviye', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=11)),
            ],
        ),
    ]
