# Generated by Django 3.2.13 on 2023-11-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gelisimTakip', '0002_ipsumuyebilgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipsumuyetip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50)),
                ('vki', models.IntegerField()),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtip', to='gelisimTakip.ipsumuye')),
            ],
        ),
    ]
