# Generated by Django 3.2.13 on 2023-11-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gelisimTakip', '0003_ipsumuyetip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipsumuyeodeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odeme', to='gelisimTakip.ipsumuye')),
            ],
        ),
    ]
