# Generated by Django 3.2.13 on 2023-12-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelisimTakip', '0004_ipsumuyeodeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsumuye',
            name='pp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
