# Generated by Django 3.2.13 on 2023-12-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelisimTakip', '0005_ipsumuye_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsumuye',
            name='cv',
            field=models.CharField(default='', max_length=100),
        ),
    ]
