# Generated by Django 3.2.13 on 2023-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelisimTakip', '0006_ipsumuye_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsumuyetip',
            name='vki',
            field=models.IntegerField(null=True),
        ),
    ]
